name: Build and Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/student-tracker:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/student-tracker:latest

    - name: Setup SSH access
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy and run Docker container on VM
      run: |
        ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} << EOF
          docker pull ${{ secrets.DOCKER_USERNAME }}/student-tracker:latest
          docker rm -f student-tracker || true
          docker run -d --name student-tracker -p 8000:8000 \
            -e VAULT_ADDR=${{ secrets.VAULT_ADDR }} \
            -e VAULT_ROLE_ID=${{ secrets.VAULT_ROLE_ID }} \
            -e VAULT_SECRET_ID=${{ secrets.VAULT_SECRET_ID }} \
            ${{ secrets.DOCKER_USERNAME }}/student-tracker:latest
          docker ps
          curl -s http://localhost:8000 || echo "App not reachable yet"
        EOF
